### PR TITLE
feat: add RC4 implementation

### PR DESCRIPTION
**Pull request by magic-akari**

### CODE REVIEW

**Comment by magic-akari** [comment]
It's hard to implement `NewCipher` for Rc4 since Rc4 can use variable key lengths.
What do you think about it? @tarcieri

**Comment by tarcieri** [comment]
@magic-akari you can make the `NewCipher` impl generic around a key size, and use a marker trait to determine the set of valid key sizes

See how `AesGcm` is similarly generic around a `NonceSize` as a roughly analogous example:

https://docs.rs/aes-gcm/latest/aes_gcm/struct.AesGcm.html

**Comment by magic-akari** [comment]
https://github.com/RustCrypto/stream-ciphers/blob/0b9ebe8f535bdc894064227e56472fb51c94399c/rc4/src/lib.rs#L128-L146

HI, @tarcieri ,
I tried to implement NewCipher, but it would be a pain for users to use.

User have to write `Rc4::new(b"Key".into(), &Default::default());` or `Rc4::<U3>::new_from_slices(b"Key", Default::default())`

`<U3>` cannot be inferred and must be written manually.

While as a user, I prefer the following codes.
What do you think about it?
https://github.com/RustCrypto/stream-ciphers/blob/6321600793376ea3e2024694f446d03800a4b681/rc4/src/lib.rs#L119-L125

**Comment by tarcieri** [comment]
@magic-akari the root problem there is really `generic-array`, and yes, its ergonomics are bad. Long term we'd like to get rid of it, and in the medium term perhaps we can replace it with https://github.com/RustCrypto/utils/pull/707

However, I think it would still make sense to impl `NewCipher`.

Users should define a type alias with the expected key size, or the crate can define some aliases for common key sizes:

```rust
pub type Rc4_128 = Rc4<U16>;
```

**Comment by newpavlov** [comment]
Can you please update this crate to `cipher v0.4`? I will try to review it next week.

**Comment by magic-akari** [comment]
HI, @newpavlov 
I tried to update it. I have to say it's hard to implement `StreamCipherCore` as it require a `BlockSize`.
Do you have any idea about it?
What `BlockSize` should Rc4 use?

**Comment by newpavlov** [comment]
Well, strictly speaking RC4 has block size of one byte. Implementation of [`StreamBackend::gen_ks_block`](https://docs.rs/cipher/latest/cipher/trait.StreamBackend.html#tymethod.gen_ks_block) would look rougly like this:
```rust
fn gen_ks_block(&mut self, block: &mut Block<Self>) {
    // `block` has type of `GenericArray<u8, U1>`
    block[0] = self.state.prga();
}
```

Alternatively you could implement the `StreamCipher` trait directly.

**Comment by magic-akari** [comment]
@newpavlov can you review it?

**Comment by tarcieri** [comment]
I can do a first pass this weekend

**Comment by tarcieri** [comment]
Looks good, thank you!

I'm going to do some minor followup cleanups after merging.

**Comment by tarcieri** [comment]
See #299 for fixups

**Pull request merged**
