### PR TITLE
chacha20: AVX2 detection

### PR DESCRIPTION
**Pull request by tarcieri**
Automatically detects the availability of AVX2 on x86(_64) architectures based on CPUID, and falls back to the SSE2" backend if unavailable.

### CODE REVIEW

**Review by newpavlov — COMMENTED** [review]
I don't think this code is correct. You can not assume that SSE2 is available without checking it either via `cfg`s or via runtime detection. It should be quite easy to add a second token which would check SSE2 feature and will use the software fallback if it's for some reason is not available. For most builds it will be replaced by `true`, so compiler should remove the fallback code for them.

**Comment by tarcieri** [comment]
@newpavlov I'm trying to find a reference for it, but I believe the `sse2` target feature is enabled-by-default on x86(_64) targets

**Comment by newpavlov** [comment]
Yes, it is, thus my comment about second token being replaced by `true` at compile time. But nothing prevents users from using `target-feature=-sse2`.

**Comment by tarcieri** [comment]
> It should be quite easy to add a second token which would check SSE2 feature and will use the software fallback if it's not available for some reason. 

Under what conditions would that target feature be absent, short of someone explicitly going out of their way to make it happen?

I added explicit target feature gating which handles this case the same way `force-soft` would.

**Review by newpavlov — APPROVED** [review]

**Pull request merged**
