### PR TITLE
[WIP] Fix ChaCha20 seeking

### PR DESCRIPTION
**Pull request by tarcieri**
This migrates the tests used by the `chacha20` crate to use the `new_sync_test!` macro.

The "core" tests are now passing, however it appears the existing
seeking implementation is broken:

```
    running 5 tests
    test chacha20_offsets ... ignored
    test chacha20_legacy_seek ... FAILED
    test chacha20_seek ... FAILED
    test chacha20_core ... ok
    test chacha20_legacy_core ... ok

    failures:

    ---- chacha20_legacy_seek stdout ----
    thread 'chacha20_legacy_seek' panicked at 'slice index starts at 65 but ends at 64', src/libcore/slice/mod.rs:2575:5
```

Now that the bug is captured, I think I have an idea of an interesting way to fix it...

### CODE REVIEW

**Comment by tarcieri** [comment]
@newpavlov sidebar, but is there any particular reason that `new_sync_test!` / `new_seek_test!` don't just work on the equivalent hex version of the same file format that `convert` uses for input?

It seems easier to work with, particularly for things like reviewing git commits, and with a little work could even permit things like comments.

**Comment by newpavlov** [comment]
@tarcieri 
Test vectors are quite rarely modified, so I thought disadvantages of a binary format will not be that significant in our case. Other than that I had two motivations for introducing it:
1) Size reduction. Some hash test vectors were quite sizable and since we include tests to a packaged crate (e.g. to be used by crater), it will reduce amount of data which has to be downloaded by users.
2) Make tests `no_std` friendly. Right now we don't use it, but tests can be ported to allocator-less targets quite effortlessly.

**Comment by newpavlov** [comment]
Maybe move `chacha20_offsets` to a separate file with `#![cfg(feature = "legacy")]`? This way you will be able to remove bunch of `#[cfg(feature = "legacy")]`.

**Comment by tarcieri** [comment]
Well, I thought I had a fun idea which isn't going to pan out because it seems `Ctr128` is specialized for a 128-bit block size, not just a 128-bit counter size. I was going to try making an internal-only pseudo-`BlockCipher` type for the ChaCha20 core function so I could try to leverage `Ctr128` to do the seeking, but it seems with a 512-bit "block" size that isn't going to pan out.

@newpavlov I think we're going to need a `Ctr32` soon as it were (since I would also like to impl AES-GCM and AES-GCM-SIV, at least as soon as I finish up POLYVAL). I'm curious if either or both of the above could be made generic around a block size. I don't think we could assert at compile time that the block size is sufficiently large for the counter, but it could immediately crash if the block size is too small for the counter...

**Comment by tarcieri** [comment]
Here's where it's blowing up:

```
   9:        0x1019b3bfe - <byteorder::LittleEndian as byteorder::ByteOrder>::read_u64::hf3a62f597aaeca40
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/slice/mod.rs:2744
  10:        0x1019b3b41 - <byteorder::LittleEndian as byteorder::ByteOrder>::read_u64::hf3a62f597aaeca40
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/slice/mod.rs:2827
  11:        0x1019b4794 - core::num::<impl usize>::max_value::h7170b1921edbc82d
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/slice/mod.rs:2552
  12:        0x1019730c1 - chacha20::chacha20_seek::h1ed4202dc1db0eb8
                               at /Users/bascule/src/RustCrypto/stream-ciphers/<::stream_cipher::dev::new_seek_test macros>:11
  13:        0x101973540 - chacha20::chacha20_seek::{{closure}}::h21324396321e10d0
                               at /Users/bascule/src/RustCrypto/stream-ciphers/<::stream_cipher::dev::new_seek_test macros>:2
```

Let me push up a commit without the seek tests, then I'll try adding them back in a followup

**Comment by tarcieri** [comment]
@newpavlov I'm a bit confused by the stack trace, but I think this is crashing inside of "blobby"? It's the only plausible candidate I have for something doing `ByteOrder::read_u64`.

Curiously, the sync tests are fine, but the seek tests fail...

**Comment by newpavlov** [comment]
My guess is that you have a test vector with a plaintext smaller than 512 bytes. I should've used `smp::min(plaintext.len() - 1, 512)` instead of 512 [here](https://github.com/RustCrypto/traits/blob/master/stream-cipher/src/dev.rs#L59)...

I will push a fix in several hours.

**Comment by tarcieri** [comment]
@newpavlov cool, I'll put the current seek tests back for now and note we should migrate to them

**Comment by tarcieri** [comment]
Will open a new PR with the test changes

**Pull request closed without merging**
