### PR TITLE
Fixed linear masking in hc-256

### PR DESCRIPTION
**Pull request by quentin-k**
In hc-256 0.4.1, linear masking isn't applied when the `h2` method is being used.

### CODE REVIEW

**Comment by newpavlov** [comment]
Hm, I wonder why both variants do not trigger on the test vectors... I will need to check HC-256 specification and compare with our implementation before merging this.

cc @emc2

**Comment by quentin-k** [comment]
The reason the variants do not trigger on the test vector is that the linear masking does not modify the p and q tables, only the output. Since only 32 bytes are tested the non linear masking code doesn't get applied. If the test vectors tested between 4096 and 8192 it would fail the test.

**Comment by quentin-k** [comment]
I have made extended the test vectors to be 8192 bytes. The following files will pass the fixed library, but fail the unfixed library, the files are also equal to the first 32 bytes of each original test vector, they are compressed into 
[long_vector_byte_files.zip](https://github.com/RustCrypto/stream-ciphers/files/7951503/long_vector_byte_files.zip).

**Comment by quentin-k** [comment]
I was looking over my code, and am going to close the pull request unless I can modify it since I disn't fully fix `h2`. It is currently
```rust
#[inline]
    fn h2(&self, x: u32) -> u32 {
        self.qtable[(x & 0xff) as usize]
            .wrapping_add(self.ptable[(256 + ((x >> 8) & 0xff)) as usize])
            .wrapping_add(self.ptable[(512 + ((x >> 16) & 0xff)) as usize])
            .wrapping_add(self.ptable[(768 + ((x >> 24) & 0xff)) as usize])
    }
```
instead of
```rust
#[inline]
    fn h2(&self, x: u32) -> u32 {
        self.ptable[(x & 0xff) as usize]
            .wrapping_add(self.ptable[(256 + ((x >> 8) & 0xff)) as usize])
            .wrapping_add(self.ptable[(512 + ((x >> 16) & 0xff)) as usize])
            .wrapping_add(self.ptable[(768 + ((x >> 24) & 0xff)) as usize])
    }
```

**Pull request closed without merging**
