### PR TITLE
Added rfc7539-section-242 test

### PR DESCRIPTION
**Pull request by seanybaggins**
Not 100% sure if the test was put in the correct location. Comments welcome.

### CODE REVIEW

**Comment by tarcieri** [comment]
Hmm, I'm not sure if these are the same vectors that are already in the (sadly opaque) `chacha20.blb` file.

Unfortunately there's not good tooling for inspecting those files.

Looking at a dump in `xxd`, possibly not?

**Comment by seanybaggins** [comment]
I fail to see the text vectors using [hexdump](https://man.archlinux.org/man/hexdump.1) and grepping for the first 2 bytes of the plain text.

```bash
hexdump -x chacha20.blb | awk '{$1=""}1' | tr -d " \t\n\r" | rg 4c61
```

**Comment by tarcieri** [comment]
Curious how the RFC7539 vectors compare to the RFC8439 test vectors: https://datatracker.ietf.org/doc/html/rfc8439#appendix-A

I can look a bit more in depth later.

**Comment by seanybaggins** [comment]
So I have looked into the differences between [rfc7539](https://datatracker.ietf.org/doc/html/rfc7539#section-2.4.2) and [rfc8439](https://datatracker.ietf.org/doc/html/rfc8439). It looks that these two tests are exactly the same. I will change the name of the test to reflect the more up to date rfc.

**Comment by tarcieri** [comment]
As it were, someone else opened #245 to add the RFC 8439 test vectors 😅 

Now I need to go through the `.blb` file and reconcile which vectors are already in there and which ones were missing, as at least upon first glance there are some missing but they're very hard to inspect and have no comments.

**Comment by tarcieri** [comment]
Closing in favor of #245 which uses the RFC 8439 test vectors.

**Pull request closed without merging**
